### ISSUE TITLE
[BUG] Unable to start v6.0.0

### ISSUE THREAD

**Issue by SonGokussj4** [Moosync/Moosync#164]
**Describe the bug**
I can't start the newest version

When run from the terminal:

```
$ moosync 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/Moosync/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/opt/Moosync/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/opt/Moosync/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)
````

- OS: Rocky Linux 8.6, Gnome
- Version: 4.18.0-372.19.1.el8_6.x86_64

**Comment by Ovenoboyo** [comment]
Could you check your GLibC version? You can do that by running ```ldd --version```
The output would be something like 
```
ldd (GNU libc) 2.XX
...
```

**Comment by SonGokussj4** [comment]
I've got older. 

```r
$ ldd --version
ldd (GNU libc) 2.28
```

We're in a company workspace so I can't just "update" like I could in my personal PC.
The previous version was without a problem.

**Comment by Ovenoboyo** [comment]
Ah I see, I recently upgrade the CI to Ubuntu from 18.04 to 20.04 which uses Glibc 2.29. Which is why the new requirement for the linux packages became 2.29. I'll try to use rocky linux 8 for the CI instead of Ubuntu. This should keep the package not too outdated.

**Comment by Ovenoboyo** [comment]
try using [this build](https://github.com/Moosync/Moosync/actions/runs/3388255965). Let me know if it works or not

**Comment by SonGokussj4** [comment]
> try using [this build](https://github.com/Moosync/Moosync/actions/runs/3388255965). Let me know if it works or not

Not sure how to use these builds. Before I've always installed it through `dnf install Moonsync_xxx.rpm`

Now I downloaded `tar.gz.zip`, unzipped, untargz, run `moonsync`

```bash
$ ll
total 302176
drwxr-xr-x. 2 myusername statikau      4096 Nov  4 13:14 locales/
drwxr-xr-x. 3 myusername statikau        47 Nov  4 13:14 resources/
-rw-r--r--. 1 myusername statikau    130050 Nov  3 19:25 chrome_100_percent.pak
-rw-r--r--. 1 myusername statikau    181273 Nov  3 19:25 chrome_200_percent.pak
-rwxr-xr-x. 1 myusername statikau   1160152 Nov  3 19:25 chrome_crashpad_handler
-rwxr-xr-x. 1 myusername statikau     52816 Nov  3 19:25 chrome-sandbox
-rw-r--r--. 1 myusername statikau  10451040 Nov  3 19:25 icudtl.dat
-rwxr-xr-x. 1 myusername statikau    250840 Nov  3 19:25 libEGL.so
-rwxr-xr-x. 1 myusername statikau   2945968 Nov  3 19:25 libffmpeg.so
-rwxr-xr-x. 1 myusername statikau   6460536 Nov  3 19:25 libGLESv2.so
-rwxr-xr-x. 1 myusername statikau   4353928 Nov  3 19:25 libvk_swiftshader.so
-rwxr-xr-x. 1 myusername statikau   6324144 Nov  3 19:25 libvulkan.so.1
-rw-r--r--. 1 myusername statikau      1096 Nov  3 19:25 LICENSE.electron.txt
-rw-r--r--. 1 myusername statikau   6648298 Nov  3 19:25 LICENSES.chromium.html
-rwxr-xr-x. 1 myusername statikau 158959544 Nov  3 19:25 moosync
-rw-r--r--. 1 myusername statikau   5433450 Nov  3 19:25 resources.pak
-rw-r--r--. 1 myusername statikau    419816 Nov  3 19:25 snapshot_blob.bin
-rw-r--r--. 1 myusername statikau    727600 Nov  3 19:25 v8_context_snapshot.bin
-rw-r--r--. 1 myusername statikau       107 Nov  3 19:25 vk_swiftshader_icd.json
(myusername@tacticus) - (~/Downloads/Moosync-6.0.0-linux-x64) $ ./moosync 
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: Cannot access 'Vt' before initialization
    at Jt (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:2:134424)
    at ye.verifySong.notifyExtensionHostPlaylistChanged (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:2:67094)
    at ye.verifySong.createPlaylist (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:2:67468)
    at 27709 (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:2:70757)
    at __webpack_require__ (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:8:724206)
    at /home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:8:726083
    at Object.<anonymous> (/home/myusername/Downloads/Moosync-6.0.0-linux-x64/resources/app.asar/index.js:8:726111)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

**Comment by Ovenoboyo** [comment]
I'm not sure why this happens... Try running the app again. If it does not work, head over to ~/.config/moosync/databases and remove all files there (This would remove the data in your library including songs, playlists, artists, albums)

**Comment by SonGokussj4** [comment]
Oh, you are right. After the second run it worked well :-)
Weird.

**Comment by Artaud** [comment]
Just came here to report a similar issue. Downloaded v6.0.0 on Ubuntu 20.04 and on the first run I got:
```
artaud@artaud-Inspiron-5491-2n1:~/Downloads/temp$ moosync
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: Cannot access 'Vt' before initialization
    at Jt (/opt/Moosync/resources/app.asar/index.js:2:133073)
    at ye.verifySong.notifyExtensionHostPlaylistChanged (/opt/Moosync/resources/app.asar/index.js:2:67021)
    at ye.verifySong.createPlaylist (/opt/Moosync/resources/app.asar/index.js:2:67395)
    at 31733 (/opt/Moosync/resources/app.asar/index.js:2:70684)
    at __webpack_require__ (/opt/Moosync/resources/app.asar/index.js:8:724206)
    at /opt/Moosync/resources/app.asar/index.js:8:726083
    at Object.<anonymous> (/opt/Moosync/resources/app.asar/index.js:8:726111)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

I thought it's screwed but this thread prodded me to try once again - on second run it started alright. So I guess this could avert potential users...

**Comment by Ovenoboyo** [comment]
I agree, it should probably be fixed in 4bd489f3d421e3a11f183f879240f0f9dbdb89e4 and be fixed from the next release and in recent CI builds as well
