### ISSUE TITLE
Tray icon is duplicated when closing the application

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#82]
**Describe the bug**
Moosync icon is duplicated in the System Tray when closing the application

**To Reproduce**
1. Open Moosync.
2. Press the button to close the application so that it is minimized in the Tray.
3. Press "Show App"

**Expected behavior**
By pressing "Show App" the previous icon would disappear and the application would return to its original state/size..

**Screenshots**
https://imgur.com/a/bS1qvm9

- OS: Linux
-Debian 11.3

**Additional context**
Nothing.

**Comment by Ovenoboyo** [comment]
@Terkyz I wasn't able to replicate this behaviour on Manjaro + Cinnamon. For me the tray icon disappears after "Show app" is pressed.

Could you try running Moosync with ```DEBUG_LOGGING=true moosync``` and see if some error spews out when pressing "Show app" or while minimizing to tray

**Comment by Terkyz** [comment]
```
kym  ~  DEBUG_LOGGING=true moosync
[04-24-2022 13:00:49] [DEBUG] [Main]:  [{"key":"startOnStartup","title":"Start app on system startup","enabled":false},{"key":"minimizeToTray","title":"Minimize to tray on close","enabled":true},{"key":"hardwareAcceleration","title":"Use GPU hardware acceleration","enabled":false},{"key":"watchFileChanges","title":"Watch music directories for changes","enabled":false},{"key":"use_invidious","title":"Use Invidious instead of Youtube","enabled":false}]
[04-24-2022 13:00:49] [DEBUG] [Main]:  Disabling hardware acceleration

DevTools listening on ws://127.0.0.1:34159/devtools/browser/48349572-aab5-4fbf-8fbd-03289c85ea48
[04-24-2022 13:00:49] [ERROR] [Main]:  null
[3825:0424/130049.304002:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[3825:0424/130049.307869:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[04-24-2022 13:00:49] [WARN] [Main]:  Cache file /home/kym/.cache/moosync/youtube.cache does not exists (This may happen if the app is run for the first time).
[04-24-2022 13:00:49] [WARN] [Main]:  Cache file /home/kym/.cache/moosync/lastfm.cache does not exists (This may happen if the app is run for the first time).
[04-24-2022 13:00:49] [WARN] [Main]:  Cache file /home/kym/.cache/moosync/invidious.cache does not exists (This may happen if the app is run for the first time).
[04-24-2022 13:00:49] [WARN] [Main]:  Cache file /home/kym/.cache/moosync/azlyrics.cache does not exists (This may happen if the app is run for the first time).
[04-24-2022 13:00:49] [DEBUG] [Renderer]:  Got song change request for extension host
[04-24-2022 13:00:49] [DEBUG] [Renderer]:  Song is missing playback url
[04-24-2022 13:00:49] [INFO] [Main]:  Checking for update
[04-24-2022 13:00:49] [ERROR] [Main]:  Error: Error: ENOENT: no such file or directory, open '/opt/Moosync/resources/app-update.yml'
[04-24-2022 13:00:49] [ERROR] [Main]:  ENOENT: no such file or directory, open '/opt/Moosync/resources/app-update.yml'Error: ENOENT: no such file or directory, open '/opt/Moosync/resources/app-update.yml'
[04-24-2022 13:00:49] [DEBUG] [Renderer]:  Got song change request for extension host
[04-24-2022 13:00:49] [DEBUG] [Extension Host]:  Received message from main process extra-extension-events
[04-24-2022 13:00:49] [DEBUG] [Extension Host]:  Received message from main process extra-extension-events
[04-24-2022 13:00:49] [DEBUG] [Extension Host]:  Received message from main process extra-extension-events
[04-24-2022 13:00:50] [DEBUG] [Extension Host]:  Received message from main process extra-extension-events
[04-24-2022 13:00:50] [ERROR] [Renderer]:  TypeError Cannot read properties of null (reading 'id') TypeError: Cannot read properties of null (reading 'id')
    at moosync://./js/727.9f2c470d.js:1:104719
    at s.ze [as _l] (moosync://./js/chunk-vendors.08f9d5a9.js:468:17107)
    at s.Jn (moosync://./js/727.9f2c470d.js:1:104660)
    at s.t._render (moosync://./js/chunk-vendors.08f9d5a9.js:468:23988)
    at s.r (moosync://./js/chunk-vendors.08f9d5a9.js:468:28029)
    at sr.get (moosync://./js/chunk-vendors.08f9d5a9.js:468:30914)
    at new sr (moosync://./js/chunk-vendors.08f9d5a9.js:468:30832)
    at Bn (moosync://./js/chunk-vendors.08f9d5a9.js:468:28043)
    at s.Er.$mount (moosync://./js/chunk-vendors.08f9d5a9.js:468:71645)
    at s.Er.$mount (moosync://./js/chunk-vendors.08f9d5a9.js:468:95739)
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onTimeUpdate callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onError callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onStateChange callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onLoad callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onBuffer callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Unloading audio
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Loading new song it's different & Helen - Tell Me YOUTUBE
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Changing player type to YOUTUBE
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Unloading audio
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onTimeUpdate callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onError callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onStateChange callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onLoad callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set onBuffer callback
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  PlaybackUrl for song JRo4TtY8DRs is JRo4TtY8DRs
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Loaded song at JRo4TtY8DRs
[04-24-2022 13:00:50] [ERROR] [Renderer]:  TypeError Cannot read properties of null (reading 'id') TypeError: Cannot read properties of null (reading 'id')
    at moosync://./js/727.9f2c470d.js:1:104719
    at s.ze [as _l] (moosync://./js/chunk-vendors.08f9d5a9.js:468:17107)
    at s.Jn (moosync://./js/727.9f2c470d.js:1:104660)
    at s.t._render (moosync://./js/chunk-vendors.08f9d5a9.js:468:23988)
    at s.r (moosync://./js/chunk-vendors.08f9d5a9.js:468:28029)
    at sr.get (moosync://./js/chunk-vendors.08f9d5a9.js:468:30914)
    at sr.run (moosync://./js/chunk-vendors.08f9d5a9.js:468:31647)
    at tr (moosync://./js/chunk-vendors.08f9d5a9.js:468:29854)
    at Array.<anonymous> (moosync://./js/chunk-vendors.08f9d5a9.js:468:12897)
    at de (moosync://./js/chunk-vendors.08f9d5a9.js:468:12292)
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set navigator mediaSession info {"title":"it's different & Helen - Tell Me","artist":"Trap Nation","album":null,"artwork":[{"src":"http://inv.riverside.rocks:3000/vi/JRo4TtY8DRs/mqdefault.jpg"},{"src":"http://inv.riverside.rocks:3000/vi/JRo4TtY8DRs/maxres.jpg"}]}
[04-24-2022 13:00:50] [DEBUG] [Renderer]:  Set navigator mediaSession action handlers

```

**Comment by Ovenoboyo** [comment]
I see some errors but not sure if they are related to your issue. I'll have a look into this more. Will keep you updated
